com

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -35,7 +35,7 @@ jobs:
       run: cobc -m -fdebugging-line MAIN.cob -lsqlite3
     - name: compil - TEST-SUM
       run: |
-        cobc -x -fdebugging-line -o test_sum TEST-SUM.cob sqlite3.o MAIN.so -lsqlite3
+        cobc -x -o test_sum TEST-SUM.cob sqlite3.o MAIN.so -lsqlite3
     - name: Ls
       run: ls
     - name: Env
@@ -46,7 +46,10 @@ jobs:
       run: |
         ./test_sum
         echo $?
-        if [ $? -e 21 ]; then
+        if [[ $? =~ 21 ]]; then
           echo "Tests Succeed"
           exit 0
+        else
+          echo "Tests Failed"
+          exit 1
         fi
